# Generated by Django 4.2.15 on 2024-08-16 04:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("concert", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="concert",
            name="city",
            field=models.CharField(default="Unknown City", max_length=255),
        ),
        migrations.AddField(
            model_name="concert",
            name="concert_name",
            field=models.CharField(default="Unknown name", max_length=255),
        ),
        migrations.AddField(
            model_name="concert",
            name="date",
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="concert",
            name="duration",
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name="concertattending",
            name="concert",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendees",
                to="concert.concert",
            ),
        ),
    ]
